### ISSUE TITLE
exposing text segmentation algos

### ISSUE THREAD

**Issue by cmyr** [servo/rust-icu#1]
Hello all,

I'm looking to use ICU's [boundary analysis](http://userguide.icu-project.org/boundaryanalysis) and I thought here might be a good place to start, but I wanted to check that this project was alive. :)

**Comment by mbrubeck** [comment]
This project isn't actively maintained, and as far as I know no one is currently using it.  However, I'm happy to accept patches, or to transfer the crate to a new maintainer.

Note: `icu-sys` is not on crates.io because I had trouble getting it under the 10MB size limit. If you want to use it from crates.io, we might need to remove the build-from-source option.

**Comment by cmyr** [comment]
@mbrubeck: Thanks for getting back to me, I've figured out an alternative solution. Will close. 👌
